POST http://localhost:8080/students
Content-Type: application/json

{
  "name": "Suletha",
  "age": 33
}

###
GET http://localhost:8080/students

###

GET http://localhost:8080/students/1

###

DELETE http://localhost:8080/students/1